version: "3"

services:
  app:
    image: mavedb-api/mavedb-api:dev
    build:
      context: .
    command: bash -c "uvicorn mavedb.server_main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    env_file:
      - settings/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8002:8000"
    volumes:
      - .:/code

  db:
    image: postgres:14
    env_file:
      - settings/.env.dev
    ports:
      - "5434:5432"
    volumes:
      - mavedb-data-dev:/var/lib/postgresql/data

#  rabbitmq:
#    image: rabbitmq:3.8.3
#    ports:
#      - "5673:5672"

volumes:
  mavedb-data-dev:
