version: "3"

services:
  app:
    image: mavedb-api/mavedb-api:dev
    build:
      context: .
#      args:
#        DJANGO_REQUIREMENTS: development
    volumes:
      - .:/code
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
#    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
#      - $PWD:/srv/src
#      - $PWD/logs:/var/log/celery
#      - /srv/src/docs
#    env_file:
#      - settings/.settings-development.env
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432

      DB_DATABASE_NAME: mavedb_dev
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
#      - APP_VERSION=development
#      - ENVIRONMENTdd=development
#      - DJANGO_SETTINGS_MODULE=settings.development

  db:
    image: postgres:14
#    build:
#      context: docker/postgres
  #  volumes:
  #    - database-data:/var/lib/postgresql/data
  #    - $PWD/docker/postgres/dumps:/home/dumps:ro
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mavedb_dev

#  rabbitmq:
#    image: rabbitmq:3.8.3
#    ports:
#      - "5673:5672"

#  volumes:
#    database-data:
